;' $Header:   P:/PVCS/386SWAT/SWAT_DBG.INV   1.3   10 Aug 1998 11:00:56   BOB  $
;
; (C) Copyright 1987-98 Qualitas, Inc.	All rights reserved.
;
; SWAT_DBG.INC
;
; Equates for DBG_FLAG
;

@DBG_CAPS    equ 8000h		; DEBUG=CAPS
@DBG_INT     equ 4000h		; DEBUG=INT
@DBG_VMS     equ 2000h		; DEBUG=VMS
@DBG_IBV     equ 1000h		; DEBUG=IBV
@DBG_VMI     equ 0800h		; DEBUG=VMI
@DBG_PMI     equ 0400h		; DEBUG=PMI
@DBG_VCNT    equ 0200h		; VMSCOUNT specified
@DBG_TRIP    equ 0100h		; DEBUG=TRIP

