;' $Header:   P:/PVCS/SWATVXD/SWATVER.INV   1.3   10 Aug 1998 10:46:20   BOB  $
;
; (C) Copyright 1990-98 Qualitas, Inc.	All rights reserved.
;
; SWATVER.INC
;
; Include file for SWATVXD Beta version numbering scheme
;

	 extrn	 SWAT_VER:abs, SWAT_VERH:abs, SWAT_VERL:abs
	 extrn	 SWAT_VERS_H:abs, SWAT_VERS_T:abs, SWAT_VERS_U:abs

SWATCOPY equ	<'   (C) Copyright 1990-8 Qualitas, Inc.  All rights reserved.'>

