;' $Header:   P:/PVCS/386SWAT/SWAT_AR2.INV   1.3   30 Jul 1994 11:22:58   BOB  $
;
; (C) Copyright 1992-2003 Qualitas, Inc.  All rights reserved.
;
; SWAT_AR2.INC
;
; Equates for AR2_FLAG
;

@AR2_STACK    equ 8000h 	; TRAPSTACK
@AR2_NORMLIDT equ 4000h 	; NORMLIDT
@AR2_DPMITMP  equ 2000h 	; Temporary DPMI services
@AR2_TSS      equ 1000h 	; TRAPTSS
@AR2_XIRQCODE equ 0800h 	; XIRQCODE

